# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProbarModelos.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from Datos.Datos import Datos
from backpropagation.Prueba import RedNeuronal
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
import pickle
from SVM import PruebaSVM
from SVM.plot_roc import Plot_roc
import numpy as np
import math

class Ui_ProbarModelo(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 631, 101))
        self.label.setObjectName("label")
        self.ProbarBackpropagation = QtWidgets.QPushButton(self.centralwidget)
        self.ProbarBackpropagation.setGeometry(QtCore.QRect(60, 130, 151, 23))
        self.ProbarBackpropagation.setObjectName("ProbarBackpropagation")
        self.ProbarBackpropagation.clicked.connect(self.ProbarModeloBackpropagation)
        self.ProbarGeneticos = QtWidgets.QPushButton(self.centralwidget)
        self.ProbarGeneticos.setGeometry(QtCore.QRect(240, 130, 151, 23))
        self.ProbarGeneticos.setObjectName("ProbarGeneticos")
        self.ProbarGeneticos.clicked.connect(self.ProbarModeloAlgoritmoGeneticos)
        self.ProbarSVM = QtWidgets.QPushButton(self.centralwidget)
        self.ProbarSVM.setGeometry(QtCore.QRect(430, 130, 151, 23))
        self.ProbarSVM.setObjectName("ProbarSVM")
        self.ProbarSVM.clicked.connect(self.ProbarModeloSVM)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 200, 521, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.VP = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VP.setObjectName("VP")
        self.gridLayout.addWidget(self.VP, 2, 2, 1, 1)
        self.FP = QtWidgets.QLabel(self.gridLayoutWidget)
        self.FP.setObjectName("FP")
        self.gridLayout.addWidget(self.FP, 2, 4, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 3, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 3, 2, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 0, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 3, 4, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 1, 1, 1, 1)
        self.FN = QtWidgets.QLabel(self.gridLayoutWidget)
        self.FN.setObjectName("FN")
        self.gridLayout.addWidget(self.FN, 4, 2, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout.addWidget(self.line_13, 2, 3, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout.addWidget(self.line_14, 4, 3, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout.addWidget(self.line_15, 3, 3, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout.addWidget(self.line_16, 1, 3, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout.addWidget(self.line_12, 0, 3, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.VN = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VN.setObjectName("VN")
        self.gridLayout.addWidget(self.VN, 4, 4, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 4, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 2, 1, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(230, 170, 341, 21))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 140, 21, 301))
        self.label_12.setObjectName("label_12")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 360, 561, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.precision = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.precision.setText("")
        self.precision.setObjectName("precision")
        self.horizontalLayout.addWidget(self.precision)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.sensibilidad = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.sensibilidad.setText("")
        self.sensibilidad.setObjectName("sensibilidad")
        self.horizontalLayout.addWidget(self.sensibilidad)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.especificidad = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.especificidad.setText("")
        self.especificidad.setObjectName("especificidad")
        self.horizontalLayout.addWidget(self.especificidad)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 470, 611, 51))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_40.setObjectName("label_40")
        self.gridLayout_2.addWidget(self.label_40, 0, 3, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_2.addWidget(self.label_42, 0, 1, 1, 1)
        self.x5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x5.setObjectName("x5")
        self.gridLayout_2.addWidget(self.x5, 1, 5, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_39.setObjectName("label_39")
        self.gridLayout_2.addWidget(self.label_39, 0, 4, 1, 1)
        self.x0 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x0.setObjectName("x0")
        self.gridLayout_2.addWidget(self.x0, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 0, 16, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 0, 14, 1, 1)
        self.x7 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x7.setObjectName("x7")
        self.gridLayout_2.addWidget(self.x7, 1, 7, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 0, 13, 1, 1)
        self.x12 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x12.setObjectName("x12")
        self.gridLayout_2.addWidget(self.x12, 1, 12, 1, 1)
        self.x11 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x11.setObjectName("x11")
        self.gridLayout_2.addWidget(self.x11, 1, 11, 1, 1)
        self.x15 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x15.setObjectName("x15")
        self.gridLayout_2.addWidget(self.x15, 1, 15, 1, 1)
        self.x13 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x13.setObjectName("x13")
        self.gridLayout_2.addWidget(self.x13, 1, 13, 1, 1)
        self.x6 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x6.setObjectName("x6")
        self.gridLayout_2.addWidget(self.x6, 1, 6, 1, 1)
        self.x14 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x14.setObjectName("x14")
        self.gridLayout_2.addWidget(self.x14, 1, 14, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 10, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 8, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 0, 17, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 11, 1, 1)
        self.x16 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x16.setObjectName("x16")
        self.gridLayout_2.addWidget(self.x16, 1, 16, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 0, 18, 1, 1)
        self.x18 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x18.setObjectName("x18")
        self.gridLayout_2.addWidget(self.x18, 1, 18, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 0, 2, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_43.setObjectName("label_43")
        self.gridLayout_2.addWidget(self.label_43, 0, 0, 1, 1)
        self.x2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x2.setObjectName("x2")
        self.gridLayout_2.addWidget(self.x2, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 7, 1, 1)
        self.x1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x1.setObjectName("x1")
        self.gridLayout_2.addWidget(self.x1, 1, 1, 1, 1)
        self.x9 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x9.setObjectName("x9")
        self.gridLayout_2.addWidget(self.x9, 1, 9, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_38.setObjectName("label_38")
        self.gridLayout_2.addWidget(self.label_38, 0, 5, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 0, 6, 1, 1)
        self.x17 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x17.setObjectName("x17")
        self.gridLayout_2.addWidget(self.x17, 1, 17, 1, 1)
        self.x3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x3.setObjectName("x3")
        self.gridLayout_2.addWidget(self.x3, 1, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 12, 1, 1)
        self.x4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x4.setObjectName("x4")
        self.gridLayout_2.addWidget(self.x4, 1, 4, 1, 1)
        self.x10 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x10.setObjectName("x10")
        self.gridLayout_2.addWidget(self.x10, 1, 10, 1, 1)
        self.x8 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.x8.setObjectName("x8")
        self.gridLayout_2.addWidget(self.x8, 1, 8, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 0, 15, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 9, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(210, 450, 211, 16))
        self.label_10.setObjectName("label_10")
        self.consultarBP = QtWidgets.QPushButton(self.centralwidget)
        self.consultarBP.setGeometry(QtCore.QRect(20, 530, 191, 23))
        self.consultarBP.setObjectName("consultarBP")
        self.consultarBP.clicked.connect(self.ConsultaBP)
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(170, 560, 81, 21))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(260, 560, 160, 21))
        self.label_45.setObjectName("label_45")
        self.consultarAG = QtWidgets.QPushButton(self.centralwidget)
        self.consultarAG.setGeometry(QtCore.QRect(230, 530, 201, 23))
        self.consultarAG.setObjectName("consultarAG")
        self.consultarAG.clicked.connect(self.ConsultaAG)
        self.consultarSVM = QtWidgets.QPushButton(self.centralwidget)
        self.consultarSVM.setGeometry(QtCore.QRect(454, 530, 161, 23))
        self.consultarSVM.setObjectName("consultarSVM")
        self.consultarSVM.clicked.connect(self.ConsultarSVM)
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(40, 410, 101, 16))
        self.label_46.setObjectName("label_46")
        self.precisionCurvaRoc = QtWidgets.QLabel(self.centralwidget)
        self.precisionCurvaRoc.setGeometry(QtCore.QRect(160, 410, 47, 13))
        self.precisionCurvaRoc.setText("")
        self.precisionCurvaRoc.setObjectName("precisionCurvaRoc")
        self.CurvaRocComparativa = QtWidgets.QPushButton(self.centralwidget)
        self.CurvaRocComparativa.setGeometry(QtCore.QRect(340, 410, 201, 23))
        self.CurvaRocComparativa.setObjectName("CurvaRocComparativa")
        self.CurvaRocComparativa.clicked.connect(self.GraficaComparativa)
        self.GenerarPrueba = QtWidgets.QPushButton(self.centralwidget)
        self.GenerarPrueba.setGeometry(QtCore.QRect(400, 450, 201, 23))
        self.GenerarPrueba.setObjectName("Generar Datos")
        self.GenerarPrueba.clicked.connect(self.GenerarDatosParaPrueba)
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(60, 340, 521, 20))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(10, 440, 621, 16))
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_19 = QtWidgets.QFrame(self.centralwidget)
        self.line_19.setGeometry(QtCore.QRect(60, 190, 521, 20))
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(self.centralwidget)
        self.line_20.setGeometry(QtCore.QRect(570, 200, 20, 151))
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.line_21 = QtWidgets.QFrame(self.centralwidget)
        self.line_21.setGeometry(QtCore.QRect(50, 200, 20, 151))
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.label.raise_()
        self.ProbarBackpropagation.raise_()
        self.ProbarGeneticos.raise_()
        self.ProbarSVM.raise_()
        self.gridLayoutWidget.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.horizontalLayoutWidget.raise_()
        self.label_8.raise_()
        self.gridLayoutWidget_2.raise_()
        self.label_10.raise_()
        self.consultarBP.raise_()
        self.GenerarPrueba.raise_()
        self.label_44.raise_()
        self.label_45.raise_()
        self.consultarAG.raise_()
        self.consultarSVM.raise_()
        self.label_46.raise_()
        self.precisionCurvaRoc.raise_()
        self.CurvaRocComparativa.raise_()
        self.line_17.raise_()
        self.line_18.raise_()
        self.line_19.raise_()
        self.line_20.raise_()
        self.line_21.raise_()
        MainWindow.setCentralWidget(self.centralwidget) 

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Probar modelos"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">Probar Modelos</span></p></body></html>"))
        self.ProbarBackpropagation.setText(_translate("MainWindow", "ANN  Backpropagation"))
        self.GenerarPrueba.setText(_translate("MainWindow", "Generar Datos"))
        self.ProbarGeneticos.setText(_translate("MainWindow", "ANN Algoritmos Genéticos"))
        self.ProbarSVM.setText(_translate("MainWindow", "SVM"))
        self.VP.setText(_translate("MainWindow", "VP"))
        self.FP.setText(_translate("MainWindow", "FP"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Positivo</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Negativo</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Positivo</span></p></body></html>"))
        self.FN.setText(_translate("MainWindow", "FN"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Matriz de confusión </span></p></body></html>"))
        self.VN.setText(_translate("MainWindow", "VN"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Negativo</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Condición verdadera</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">P<br/>r<br/>e<br/>d<br/>i<br/>c<br/>c<br/>i<br/>ó<br/>n</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Precisión:"))
        self.label_8.setText(_translate("MainWindow", "Sensibilidad:"))
        self.label_9.setText(_translate("MainWindow", "Especificidad:"))
        self.label_40.setText(_translate("MainWindow", "X3"))
        self.label_42.setText(_translate("MainWindow", "X1"))
        self.label_39.setText(_translate("MainWindow", "X4"))
        self.label_23.setText(_translate("MainWindow", "X16"))
        self.label_21.setText(_translate("MainWindow", "X14"))
        self.label_20.setText(_translate("MainWindow", "X13"))
        self.label_17.setText(_translate("MainWindow", "X10"))
        self.label_15.setText(_translate("MainWindow", "X8"))
        self.label_24.setText(_translate("MainWindow", "X17"))
        self.label_18.setText(_translate("MainWindow", "X11"))
        self.label_36.setText(_translate("MainWindow", "X18"))
        self.label_41.setText(_translate("MainWindow", "X2"))
        self.label_43.setText(_translate("MainWindow", "X0"))
        self.label_13.setText(_translate("MainWindow", "X7"))
        self.label_38.setText(_translate("MainWindow", "X5"))
        self.label_37.setText(_translate("MainWindow", "X6"))
        self.label_19.setText(_translate("MainWindow", "X12"))
        self.label_22.setText(_translate("MainWindow", "X15"))
        self.label_16.setText(_translate("MainWindow", "X9"))
        self.x0.setText(str(0))
        self.x1.setText(str(0))
        self.x2.setText(str(0))
        self.x3.setText(str(0))
        self.x4.setText(str(0))
        self.x5.setText(str(0))
        self.x6.setText(str(0))
        self.x7.setText(str(0))
        self.x8.setText(str(0))
        self.x9.setText(str(0))
        self.x10.setText(str(0))
        self.x11.setText(str(0))
        self.x12.setText(str(0))
        self.x13.setText(str(0))
        self.x14.setText(str(0))
        self.x15.setText(str(0))
        self.x16.setText(str(0))
        self.x17.setText(str(0))
        self.x18.setText(str(0))
        self.label_10.setText(_translate("MainWindow", "Hacer una categorización concreta:"))
        self.consultarBP.setText(_translate("MainWindow", "Consultar ANN con Backpropagation"))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Resultado:</span></p><p><br/></p></body></html>"))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Vacio</span></p><p><br/></p></body></html>"))
        self.consultarAG.setText(_translate("MainWindow", "Consultar ANN con algoritmo genético "))
        self.consultarSVM.setText(_translate("MainWindow", "Consultar con SVM"))
        self.label_46.setText(_translate("MainWindow", "Precisión Curva ROC:"))
        self.CurvaRocComparativa.setText(_translate("MainWindow", "Ver Curva ROC Comparativa"))


    def ProbarModeloBackpropagation(self):
        backpropagation = RedNeuronal()
        Y_resultado,y=backpropagation.ProbarModeloBackpropagation()
        fprBP, tprBP, _ = roc_curve(y, Y_resultado)
        roc_aucBP = auc(fprBP, tprBP)
        self.VP.setText(str(backpropagation.matrizDeConfusion[1][1]))
        self.FP.setText(str(backpropagation.matrizDeConfusion[1][0]))
        self.FN.setText(str(backpropagation.matrizDeConfusion[0][1]))
        self.VN.setText(str(backpropagation.matrizDeConfusion[0][0]))
        self.precision.setText(str(backpropagation.precision))
        self.sensibilidad.setText(str(backpropagation.sensitivity))
        self.especificidad.setText(str(backpropagation.specificity))
        self.precisionCurvaRoc.setText(str(roc_aucBP))

    def ProbarModeloAlgoritmoGeneticos(self):
        algoritmoGenetico = RedNeuronal()
        Y_resultado,y=algoritmoGenetico.ProbarModeloAlgoritmosGeneticos()
        fprAG, tprAG, _ = roc_curve(y, Y_resultado)
        roc_aucAG = auc(fprAG, tprAG) 
        self.VP.setText(str(algoritmoGenetico.matrizDeConfusion[1][1]))
        self.FP.setText(str(algoritmoGenetico.matrizDeConfusion[1][0]))
        self.FN.setText(str(algoritmoGenetico.matrizDeConfusion[0][1]))
        self.VN.setText(str(algoritmoGenetico.matrizDeConfusion[0][0]))
        self.precision.setText(str(algoritmoGenetico.precision))
        self.sensibilidad.setText(str(algoritmoGenetico.sensitivity))
        self.especificidad.setText(str(algoritmoGenetico.specificity))
        self.precisionCurvaRoc.setText(str(roc_aucAG))

    def ProbarModeloSVM(self):   
        SVM = PruebaSVM.SVM()
        SVM.probarKernelLineal()
        self.VP.setText(str(SVM.matrizDeConfusion[1][1]))
        self.FP.setText(str(SVM.matrizDeConfusion[1][0]))
        self.FN.setText(str(SVM.matrizDeConfusion[0][1]))
        self.VN.setText(str(SVM.matrizDeConfusion[0][0]))
        self.precision.setText(str(SVM.precision))
        self.sensibilidad.setText(str(SVM.sensitivity))
        self.especificidad.setText(str(SVM.specificity))
        self.precisionCurvaRoc.setText(str(SVM.roc_aucSVM))
        
    def GraficaComparativa(self):
        plot = Plot_roc()
        plot.plot_roc_completa()

    def ConsultaBP(self):
        entrada = [float(self.x0.text()),float(self.x1.text()),float(self.x2.text()),float(self.x3.text()),float(self.x4.text()),float(self.x5.text()),float(self.x6.text()),float(self.x7.text()),float(self.x8.text()),float(self.x9.text()),float(self.x10.text()),float(self.x11.text()),float(self.x12.text()),float(self.x13.text()),float(self.x14.text()),float(self.x15.text()),float(self.x16.text()),float(self.x17.text()),float(self.x18.text())]
        datos = Datos()
        entradaNormalizada = datos.Convertir19A55(entrada)
        backpropagation = RedNeuronal()
        backpropagation.ProbarModeloBackpropagation()
        salida,a,b,c = backpropagation.RedNeuronal1CapaOculta(entradaNormalizada)
        resultado =  "Positivo"  if round(salida) == 1 else "Negativo"
        _translate = QtCore.QCoreApplication.translate
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">"+resultado+"  "+str(salida)+"</span></p><p><br/></p></body></html>"))        
        
    def ConsultaAG(self):
        entrada =[float(self.x0.text()),float(self.x1.text()),float(self.x2.text()),float(self.x3.text()),float(self.x4.text()),float(self.x5.text()),float(self.x6.text()),float(self.x7.text()),float(self.x8.text()),float(self.x9.text()),float(self.x10.text()),float(self.x11.text()),float(self.x12.text()),float(self.x13.text()),float(self.x14.text()),float(self.x15.text()),float(self.x16.text()),float(self.x17.text()),float(self.x18.text())]
        datos = Datos()
        entradaNormalizada = datos.Convertir19A55(entrada)
        algoritmoGenetico = RedNeuronal()
        Y_resultado,y=algoritmoGenetico.ProbarModeloAlgoritmosGeneticos()
        salida,a,b,c = algoritmoGenetico.RedNeuronal1CapaOculta(entradaNormalizada)
        resultado =  "Positivo"  if round(salida) == 1 else "Negativo"
        _translate = QtCore.QCoreApplication.translate
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">"+resultado+"  "+str(salida)+"</span></p><p><br/></p></body></html>"))
    
    def ConsultarSVM(self):
        entrada =[float(self.x0.text()),float(self.x1.text()),float(self.x2.text()),float(self.x3.text()),float(self.x4.text()),float(self.x5.text()),float(self.x6.text()),float(self.x7.text()),float(self.x8.text()),float(self.x9.text()),float(self.x10.text()),float(self.x11.text()),float(self.x12.text()),float(self.x13.text()),float(self.x14.text()),float(self.x15.text()),float(self.x16.text()),float(self.x17.text()),float(self.x18.text())]
        SVM = PruebaSVM.SVM()
        salida = SVM.PredictKernelLineal(entrada)
        resultado =  "Positivo"  if round(salida) == 1 else "Negativo"
        _translate = QtCore.QCoreApplication.translate
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">"+resultado+"  "+str(salida)+"</span></p><p><br/></p></body></html>"))
    
    def GenerarDatosParaPrueba(self):
        datos = Datos()
        datos.datosConEnterosNormalizados()
        self.entradaDeseada = datos.Datos
        elementos = np.random.permutation(math.ceil(len(self.entradaDeseada)))
        self.x0.setText(str(self.entradaDeseada[elementos[0]][0]))
        self.x1.setText(str(self.entradaDeseada[elementos[0]][1]))
        self.x2.setText(str(self.entradaDeseada[elementos[0]][2]))
        self.x3.setText(str(self.entradaDeseada[elementos[0]][3]))
        self.x4.setText(str(self.entradaDeseada[elementos[0]][4]))
        self.x5.setText(str(self.entradaDeseada[elementos[0]][5]))
        self.x6.setText(str(self.entradaDeseada[elementos[0]][6]))
        self.x7.setText(str(self.entradaDeseada[elementos[0]][7]))
        self.x8.setText(str(self.entradaDeseada[elementos[0]][8]))
        self.x9.setText(str(self.entradaDeseada[elementos[0]][9]))
        self.x10.setText(str(self.entradaDeseada[elementos[0]][10]))
        self.x11.setText(str(self.entradaDeseada[elementos[0]][11]))
        self.x12.setText(str(self.entradaDeseada[elementos[0]][12]))
        self.x13.setText(str(self.entradaDeseada[elementos[0]][13]))
        self.x14.setText(str(self.entradaDeseada[elementos[0]][14]))
        self.x15.setText(str(self.entradaDeseada[elementos[0]][15]))
        self.x16.setText(str(self.entradaDeseada[elementos[0]][16]))
        self.x17.setText(str(self.entradaDeseada[elementos[0]][17]))
        self.x18.setText(str(self.entradaDeseada[elementos[0]][18]))



        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ProbarModelo()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())